#!/usr/bin/env bash
# build_single.sh — produce a single-file amalgam of the aligner.
#
#   ./tools/build_single.sh [OUT]   default: build/aligner.c
#
# The amalgam compiles with libc only:
#   cc -std=c99 -O2 -o aligner build/aligner.c
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/build/aligner.c}"

mkdir -p "$(dirname "$OUT")"

# Collect every #include <...> from src/ and shim, dedupe.
SYS_INCLUDES="$(
    {
        grep -h '^#include <' "$ROOT"/src/*.c "$ROOT"/src/*.h
        # Shim uses these:
        echo '#include <stdarg.h>'
        echo '#include <stddef.h>'
        echo '#include <stdio.h>'
        echo '#include <stdlib.h>'
        echo '#include <string.h>'
    } | sort -u
)"

{
    cat << HDR
/*
 * aligner.c — single-file build of the aligner, generated by
 * tools/build_single.sh.
 *
 * Compile and link with libc only:
 *     cc -std=c99 -O2 -o aligner aligner.c
 *
 * The full project source tree (lexer + parser + AST + passes + emit +
 * align, plus the data-structures library it depends on) lives separately
 * and is what's actually tested. This file is its concatenation, with the
 * project's own headers inlined and the ds library replaced by a minimal
 * shim covering exactly the 27 symbols the aligner uses.
 *
 * Last regenerated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
 */

HDR

    echo "$SYS_INCLUDES"
    echo

    # Shim — provides ds_ / DS_ / str_ / FUNC_str_ surface.
    cat "$ROOT/tools/shim.c"
    echo

    # Project sources, headers first then implementations. Strip local
    # includes (the quoted ones; we just concatenated the headers above).
    for f in \
        "$ROOT"/src/lexer.h \
        "$ROOT"/src/ast.h \
        "$ROOT"/src/parser.h \
        "$ROOT"/src/pass.h \
        "$ROOT"/src/emit.h \
        "$ROOT"/src/align.h \
        "$ROOT"/src/lexer.c \
        "$ROOT"/src/ast.c \
        "$ROOT"/src/parser.c \
        "$ROOT"/src/pass_destring.c \
        "$ROOT"/src/emit.c \
        "$ROOT"/src/align.c \
        "$ROOT"/src/main.c
    do
        echo
        echo "/* ============================================================"
        echo " * $(basename "$f")"
        echo " * ============================================================"
        echo " */"
        # Drop:
        #  - quoted #include "..." (project-local, all inlined here)
        #  - <...> system includes (already at the top, deduped)
        grep -v '^#include' "$f"
    done

} > "$OUT"

lines=$(wc -l < "$OUT")
bytes=$(wc -c < "$OUT")
printf 'wrote %s  (%d lines, %d bytes)\n' "$OUT" "$lines" "$bytes"
